user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

press:
    resource: "@PressBundle/Resources/config/routing.yml"
    prefix:   /
    
# Manage security
fos_user_security:
    resource:  "@FOSUserBundle/Resources/config/routing/security.xml"




