<?php

namespace PressBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository {
    
    public function getArticlesFromUser($userId) {
        $query = $this->createQueryBuilder("a")
            ->leftJoin("a.owner", "o")
            ->where("o.id = :userId")
            ->andWhere("a.archived = 0")
            ->orderBy("a.creationDate", "DESC")
            ->setParameter("userId", $userId)
            ->getQuery();

        return $query->getArrayResult();
    }
    
}
