<?php

namespace PressBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getAllTagsSorted($userId) {
        $query = $this->createQueryBuilder("t")
            ->leftJoin("t.owner", "o")
            ->orderBy("t.name", "ASC")
            ->where("o.id = :userId")
            ->setParameter("userId", $userId)
            ->getQuery();

        return $query->getArrayResult();
    }
    
    public function getFirstTagsSorted($number, $userId) {
        $query = $this->createQueryBuilder("t")
            ->addSelect("a")
            ->leftJoin("t.owner", "o")
            ->leftJoin("t.articles", "a")
            ->where("o.id = :userId")
            ->orderBy("t.name", "ASC")
            ->setFirstResult(0)
            ->setMaxResults($number - 1)
            ->setParameter("userId", $userId)
            ->getQuery();

        return $query->getResult();
    }
}
