<?php

namespace PressBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getAllTagsSorted() {
        $query = $this->createQueryBuilder("t")
            ->orderBy("t.name", "ASC")
            ->getQuery();

        return $query->getArrayResult();
    }
}
