services:
    user.mailer:
        class: UserBundle\Services\Mailer
        arguments: ["@mailer", "@templating", "%confirm_email.from%", "%confirm_email.subject%",  "%confirm_email.activation_link%"]
