press_homepage:
    path:     /
    defaults: { _controller: PressBundle:Default:index }

# Authentication controller
authentication:
    path: /authentication
    defaults: { _controller: PressBundle:Authentication:index }
   
# Architechture controller
press_architechture_get_menu_items:
    path: /frontend-api/architecture/get-menu-items
    defaults: {_controller: PressBundle:Architecture:getMenuItems }
    
# Aricles controller
press_articles_get_all:
    path:     /frontend-api/articles/get/all
    defaults: { _controller: PressBundle:Articles:getAll }
    
press_articles_get_tag:
    path:     /frontend-api/articles/get/{tagId}
    defaults: { _controller: PressBundle:Articles:getFromTag }
    requirements:
        tagId: \d+
        
press_articles_get_archived:
    path:     /frontend-api/articles/get/archived
    defaults: { _controller: PressBundle:Articles:getArchived }
    
press_articles_add:
    path: /frontend-api/articles/add
    defaults: {_controller: PressBundle:Articles:add }
    
press_articles_archive:
    path: /frontend-api/articles/archive/{articleId}
    defaults: {_controller: PressBundle:Articles:archive }
    requirements:
        articleId: \d+
        
press_articles_loadLabelsDialogDatas:
    path: /frontend-api/articles/load-labels-dialog-datas/{articleId}
    defaults: {_controller: PressBundle:Articles:loadLabelsDialogDatas }
    requirements:
        articleId: \d+

press_articles_edit_labels:
    path: /frontend-api/articles/edit-labels
    defaults: {_controller: PressBundle:Articles:editLabels }
        
press_articles_delete:
    path: /frontend-api/articles/delete/{articleId}
    defaults: {_controller: PressBundle:Articles:delete }
    requirements:
        articleId: \d+
        
# Tags controller
press_tags_add:
    path: /frontend-api/tags/add
    defaults: {_controller: PressBundle:Tags:add }
    
press_tags_get:
    path: /frontend-api/tags/get/all
    defaults: {_controller: PressBundle:Tags:getAll }
    

