press_homepage:
    path:     /
    defaults: { _controller: PressBundle:Default:index }
    
press_articles_get_all:
    path:     /frontend-api/articles/get/all
    defaults: { _controller: PressBundle:Articles:getAll }
    
press_articles_add:
    path: /frontend-api/articles/add
    defaults: {_controller: PressBundle:Articles:add }
    

