services:
    # Login, inscription et logout
    ucs.security.authentication_success_handler:
        class: PressBundle\Handler\AuthenticationSuccessHandler
    ucs.security.authentication_failure_handler:
        class: PressBundle\Handler\AuthenticationFailureHandler
    ucs.security.authentication_entry_point:
        class: PressBundle\EntryPoint\AuthenticationEntryPoint
    ucs.security.logout_success_handler:
        class: PressBundle\Handler\LogoutSuccessHandler
        
    # Services
    press.check_csrf_listener:
        class: PressBundle\Services\CheckCSRFListener
        arguments: [@security.csrf.token_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    press.site_extractor:
        class: PressBundle\Services\SiteExtractor
    press.sort_parameters_converter:
        class: PressBundle\Services\SortParametersConverter